//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The4Dimension.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The4Dimension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C1&gt;
        ///    &lt;C1 Name=&quot;Collision&quot;&gt;
        ///      &lt;A0 Name=&quot;Sensor&quot; StringValue=&quot;Collision&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;C1 Name=&quot;Debug&quot;&gt;
        ///      &lt;A0 Name=&quot;NodeName&quot; StringValue=&quot;地形&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;C1 Name=&quot;Executor&quot;&gt;
        ///      &lt;A0 Name=&quot;CategoryName&quot; StringValue=&quot;固定地形&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;C1 Name=&quot;GroupClipping&quot;&gt;
        ///      &lt;D1 Name=&quot;MaxCount&quot; StringValue=&quot;64&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;FF Name=&quot;Model&quot; StringValue=&quot; [stringa troncata]&quot;;.
        /// </summary>
        internal static string Actor {
            get {
                return ResourceManager.GetString("Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FirstStageMap1.szs
        ///CaveInkStageMap1.szs
        ///DownHillStageMap1.szs
        ///BalanceTruckStageMap1.szs
        ///KoopaFirstStageMap1.szs
        ///FieldWalkStageMap1.szs
        ///CavePatanStageMap1.szs
        ///DotCoinStageMap1.szs
        ///JumpFlipGeneratorStageMap1.szs
        ///BattleShipKillerStageMap1.szs
        ///DesertRuinStageMap1.szs
        ///AquariumSwimStageMap1.szs
        ///SkyChikuwaStageMap1.szs
        ///MountainRopeStageMap1.szs
        ///SweetsScrollStageMap1.szs
        ///FortressSpikeStageMap1.szs
        ///UpUpLandStageMap1.szs
        ///CaveClimbStageMap1.szs
        ///SkyRotateBlockStageMap1.szs
        ///FlashTeresaStageMap1.szs
        ///S [stringa troncata]&quot;;.
        /// </summary>
        internal static string AllStageList {
            get {
                return ResourceManager.GetString("AllStageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] BaseModels {
            get {
                object obj = ResourceManager.GetObject("BaseModels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] BCSTMtools {
            get {
                object obj = ResourceManager.GetObject("BCSTMtools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C1&gt;
        ///    &lt;C0 Name=&quot;CameraParams&quot;&gt;
        ///      
        ///    &lt;/C0&gt;
        ///    &lt;C1 Name=&quot;VisionParam&quot;&gt;
        ///      &lt;D2 Name=&quot;FarClipDistance&quot; StringValue=&quot;80000&quot; /&gt;
        ///      &lt;D2 Name=&quot;FovyDegree&quot; StringValue=&quot;45&quot; /&gt;
        ///      &lt;D2 Name=&quot;NearClipDistacne&quot; StringValue=&quot;100&quot; /&gt;
        ///      &lt;D2 Name=&quot;StereovisionDepth&quot; StringValue=&quot;0,4&quot; /&gt;
        ///      &lt;D2 Name=&quot;StereovisionDistance&quot; StringValue=&quot;200&quot; /&gt;
        ///    &lt;/C1&gt;
        ///  &lt;/C1&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string GenericCameraParam {
            get {
                return ResourceManager.GetString("GenericCameraParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a @echo off
        ///Title CCNT patcher
        ///cls
        ///echo This will add the object entries to the CreatorClassNameTable.szs file.
        ///echo You should make a backup of this file.
        ///echo Press enter to continue
        ///pause &gt;nul
        ///Start /W Patcher.exe CCNTpatch Done, you are ready to go !
        ///del 3DS.dll
        ///del CCNTpatch.xml
        ///del CommonCompressors.dll
        ///del CommonFiles.dll
        ///del LibEveryFileExplorer.dll
        ///del NDS.dll
        ///del Patcher.exe
        ///del &quot;Patch script.bat&quot;.
        /// </summary>
        internal static string PatchScript {
            get {
                return ResourceManager.GetString("PatchScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C0&gt;
        ///    &lt;C1&gt;
        ///      &lt;A0 Name=&quot;Name&quot; StringValue=&quot;Collision&quot; /&gt;
        ///      &lt;A0 Name=&quot;Type&quot; StringValue=&quot;CollisionParts&quot; /&gt;
        ///    &lt;/C1&gt;
        ///  &lt;/C0&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
    }
}
